@startuml
'https://plantuml.com/class-diagram
!theme cyborg
package "py-dss-interface"{
    class DSS {
    }
}

package "py-dss-tools"{
class Scenario {
    -id: int
    -created: boolean
    -name: String
    -circuit: Circuit
    -frequency_base: int
    -dss: DSS
    -logger
    -dss_file

    -void print_header()
}
class Circuit {
    -id: int
    -created: boolean
    -name: String
    -basekv: basekv
    -pu: float
    -phases: int
    -bus1: String
    -angle: float
    -mvasc3: float
    -mvasc1: float

    -df_lines()
}

Scenario "1" -- "1" Circuit: have >
Scenario "1" -- "1" DSS: have >
Circuit "1" -- "1" DSS: have >
VSource <|-- Circuit

class ControlElement{
    -basefreq: float
    -enabled: boolean
    -like: String
}

class CapControl{
    -capacitor: String
    -ctphase: String
    -ctratio: String
    -deadtime: String
    -delay: String
    -delayoff: String
    -element: String
    -eventlog: String
    -offsetting: String
    -onsetting: String
    -pctminkvar: String
    -ptphase: String
    -ptratio: String
    -reset: String
    -terminal: String
    -type: String
    -userdata: String
    -usermodel: String
    -vbus: String
    -vmax: float
    -vmin: float
    -voltoverride: String
}

ControlElement "1" <|-- "*" CapControl
ControlElement "1" <|-- "*" ESPVLControl
ControlElement "1" <|-- "*" ExpControl
ControlElement "1" <|-- "*" Fuse
ControlElement "1" <|-- "*" GenDispatcher
ControlElement "1" <|-- "*" InvControl
ControlElement "1" <|-- "*" RegCloser
ControlElement "1" <|-- "*" Relay
ControlElement "1" <|-- "*" StorageController
ControlElement "1" <|-- "*" SwtControl
ControlElement "1" <|-- "*" UPFCControl
}

@enduml
